name: parallelism
description: Parallelism (via Dart Isolates) simplified
version: 2.2.0-beta
repository: https://github.com/shady-ti/parallelism/

environment:
  sdk: ^3.0.5


dev_dependencies:
  dart_code_metrics: ^5.7.5
  lints: ^2.0.0
  test: ^1.21.0
