name: simple_process
description: A Dart package that simplifies parallelization using isolates, making it easier to run tasks concurrently and improve performance.
version: 1.0.0

repository: https://github.com/shady-ti/parallelism/

environment:
  sdk: ^3.0.5

dev_dependencies:
  dart_code_metrics: ^5.7.5
  lints: ^2.0.0
  test: ^1.21.0
